name: Build & Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.4.0
      with:
        # SDK version to use. Example: 2.2.104
        dotnet-version: 3.1.100 # optional
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Create Releases
      run: |
           sh .github/create_releases.sh
